"""edition.py - which build this is. See README_ANDROID.md's "Compact (free) edition" section.

"full"  - every screen (the default: a normal working copy, and the "full" CI build/job).
"lite"  - the free, feature-limited edition. Only FREE_SCREENS below are built; every other
          screen (yogas, dashas, the readings, predictions, doshas & remedies, family
          compatibility, the ashtakvarga/KP/shodashvarga tables, ...) is left out of Home and the
          bottom bar entirely - not shown locked, just not built - reserved for a future paid
          Premium edition of this same app.

The CI workflow (.github/workflows/build-apk.yml) flips EDITION to "lite" with a sed replace on a
FRESH checkout before packaging the lite job's APK, and builds with buildozer.spec's [app@lite]
profile (a different app title and package id, so both editions can be installed side by side on
one device). A normal working copy, and the "full" job's own checkout, are never touched and stay
"full". Do not edit this file to test the lite edition locally and then commit the change -
use `VEDIC_EDITION=lite` (see below) instead, or edit-and-revert.
"""
import os

EDITION = os.environ.get("VEDIC_EDITION", "full")   # env var override for local testing only - CI edits the line above

APP_TITLE = {"full": "Vedic Astrology", "lite": "Vedic Astrology Compact"}

# Screen keys (main.py's _registry / ui/tabs_home.py's card keys) kept in the lite edition: generate
# and view a chart (with every divisional-chart diagram), the classical placement lookups, and the
# plumbing every edition needs (saved charts, help). Everything else is Premium-only for now.
FREE_SCREENS = {"home", "entry", "library", "chart", "kundli", "planet_house", "planet_sign", "houses", "help"}


def visible(key):
    """Whether `key` (a main.py screen / ui/tabs_home.py card key) exists in this edition."""
    return EDITION == "full" or key in FREE_SCREENS
