"""i18n.py - the app's tiny, fully OFFLINE translation layer (Bengali now, Hindi later).

Every translation is a plain Python dict bundled in the APK (engine/i18n_<code>.py, generated by
tools/build_i18n.py from the readable files in i18n_src/): no network, no model. English text is its own
key, so anything without a translation simply shows in English.

  t("Home")                          exact text  -> translation, else the English itself
  tr("{0} is in your {1} house", planet, ordinal(h))
                                     a sentence built from pieces: the whole TEMPLATE is translated (so word
                                     order can follow the language) and each piece is translated and slotted in
  t_text(paragraphs)                 whole paragraphs, with a sentence-by-sentence fallback
  tbl({...})                         a table of display strings whose VALUES are translated when read
  join_list(["A", "B", "C"])         "A, B and C" in the current language

English mode is a no-op: every function returns exactly what the code would have produced before.
Bengali letters are stored as pre-shaped syllable glyphs (private-use code points) because Kivy cannot shape
Indic scripts; the matching font is registered by ui/fonts.py.
"""
import datetime as _dt
import importlib
import re
import string

LANGUAGE_CODES = ["en", "bn", "hi"]
_code = "en"
_modules = {}
_misses = None                       # set to a set() to record English text that had no translation (tests / tools)


def set_language(code):
    """Switch language. Any code with an engine/i18n_<code>.py module is accepted (tests use a pseudo language)."""
    global _code
    _code = code if code == "en" or code in LANGUAGE_CODES or _module(code) is not None else "en"


def get_language():
    return _code


def is_english():
    return _code == "en"


def start_recording_misses():
    global _misses
    _misses = set()
    return _misses


def _module(code):
    if code not in _modules:
        try:
            _modules[code] = importlib.import_module(f"i18n_{code}")
        except ImportError:
            _modules[code] = None
    return _modules[code]


def _table():
    mod = _module(_code)
    return mod.T if mod else {}


def native_name(code):
    """A language's own name in its own script (English -> "English")."""
    if code == "en":
        return "English"
    mod = _module(code)
    return getattr(mod, "NAME", code) if mod else code


def language_available(code):
    return code == "en" or _module(code) is not None


# ---------------------------------------------------------------- vocabulary rules
_ORD = re.compile(r"^(\d+)(st|nd|rd|th)$")
_BN_ORDINAL = {1: "{0}ম", 2: "{0}য়", 3: "{0}য়", 4: "{0}র্থ"}      # filled in by the generated table when present


def _rule(text):
    """Translations that follow a rule instead of a table entry: ordinals such as 12th, comma lists of known
    words ("Sun, Mar"), a retrograde mark after a planet ("SatR") and a trailing " (now)"."""
    m = _ORD.match(text)
    if m:
        pattern = _table().get("{n}th (ordinal)")
        if pattern:
            n = int(m.group(1))
            special = _table().get(f"{n}th (ordinal)")
            return special or pattern.format(n=n)
    if ", " in text and len(text) < 80:
        parts = [_lookup(p) for p in text.split(", ")]
        if all(p is not None for p in parts):
            return ", ".join(parts)
    if text.endswith(" (now)"):
        base = _lookup(text[:-6])
        now = _lookup("now")
        if base is not None and now is not None:
            return f"{base} ({now})"
    if len(text) in (4, 5) and text.endswith("R") and text[-2].islower():
        base = _lookup(text[:-1])
        if base is not None:
            return base + "R"
    return None


_arg_misses = set()
_ci_cache = {}


def _ci(table):
    """{lower-case English: translation} so that 'good', 'Good' and 'GOOD' share one entry (built once per table)."""
    key = id(table)
    if key not in _ci_cache:
        _ci_cache[key] = {k.lower(): v for k, v in table.items() if len(k) < 100}
    return _ci_cache[key]


def _lookup(text):
    """Exact match, else a case-insensitive match for short words; None if there is no translation."""
    table = _table()
    hit = table.get(text)
    if hit is None and len(text) < 100:
        hit = _ci(table).get(text.lower())
    return hit


def t(text):
    """Translate an exact English string; the string itself if there is no translation (or in English)."""
    if _code == "en" or not isinstance(text, str) or not text:
        return text
    hit = _lookup(text)
    if hit is not None:
        return hit
    ruled = _rule(text)
    if ruled is not None:
        return ruled
    if _misses is not None and re.search(r"[A-Za-z]{3,}", text):
        _misses.add(text)
    return text


tx = t            # the name used inside the app modules (a bare "t" is a common local variable there)


def t_text(text):
    """Translate a whole block: exact match first, else paragraph by paragraph, line by line and sentence by
    sentence (each piece that has a translation is replaced; the rest stays English)."""
    if _code == "en" or not isinstance(text, str) or not text.strip():
        return text
    table = _table()
    if text in table:
        return table[text]
    out_paragraphs = []
    for para in text.split("\n\n"):
        if para in table:
            out_paragraphs.append(table[para])
            continue
        lines = []
        for line in para.split("\n"):
            if not line.strip():
                lines.append(line)
            elif line in table:
                lines.append(table[line])
            else:
                lines.append(_translate_sentences(line, table))
        out_paragraphs.append("\n".join(lines))
    return "\n\n".join(out_paragraphs)


# a sentence ends at . ! ? followed by a space - except after abbreviations such as "e.g." or "vs."
_SENTENCE = re.compile(r"(?<=[.!?।])(?<!e\.g\.)(?<!i\.e\.)(?<!vs\.)(?<!etc\.)\s+")
_GIST = re.compile(r"^\[In simple terms:\s*(.*)\]([.]?)$", re.S)


def _translate_sentences(line, table):
    parts = _SENTENCE.split(line)
    danda = getattr(_module(_code), "DANDA", "")     # text already written in the language ends its sentences with this
    if danda:
        parts = [q for s in parts for q in re.split("(?<=" + re.escape(danda) + r")\s+", s)]
    done = []
    for s in parts:
        hit = table.get(s)
        if hit is None:
            m = _GIST.match(s)                                   # "[In simple terms: ...]" plain-words lines
            if m:
                inner = t_text(m.group(1))
                label = table.get("In simple terms")
                if label and inner != m.group(1):
                    hit = "[" + label + ": " + inner + "]" + m.group(2)
        if hit is None and s.endswith(".."):                     # a full stop added after text that already ends in one
            hit = table.get(s[:-1])
        if hit is None:
            hit = _rule(s)
        if hit is None:
            # "Heading: body" where only the body is a known sentence (the heading is built by the program)
            head, colon, body = s.partition(": ")
            if colon and body in table and len(head) < 90:
                lead = t(head) if head.strip() else head
                hit = lead + ": " + table[body]
        if hit is None and _misses is not None and re.search(r"[A-Za-z]{3,}", s):
            _misses.add(s)
        done.append(hit if hit is not None else s)
    return " ".join(done)


# ---------------------------------------------------------------- templates
_formatter = string.Formatter()
_BN_MONTHS = None


def _month_names():
    mod = _module(_code)
    return getattr(mod, "MONTHS", None) if mod else None


def _format_arg(value, spec, conversion):
    if conversion:
        value = {"r": repr, "s": str, "a": ascii}[conversion](value)
    if isinstance(value, (_dt.date, _dt.datetime)) and spec and _code != "en":
        names = _month_names()
        if names and ("%b" in spec or "%B" in spec):
            long_names = getattr(_module(_code), "MONTHS_LONG", names)
            spec = spec.replace("%B", "\x01").replace("%b", "\x00")
            text = value.strftime(spec)
            return text.replace("\x00", names[value.month - 1]).replace("\x01", long_names[value.month - 1])
    if isinstance(value, str) and _code != "en":
        hit = _lookup(value)
        if hit is None and _misses is not None and re.search(r"[A-Za-z]{3,}", value) and len(value) < 60:
            _arg_misses.add(value)
        if hit is None:
            hit = _rule(value)
        if hit is None and len(value) > 40 and " " in value:
            hit = t_text(value)                                  # a knowledge-base paragraph passed into a template
            if hit == value:
                hit = None
        value = hit if hit is not None else value
        if spec:
            return format(value, spec)
        return value
    return format(value, spec) if spec else str(value)


_DISPLAY_ONLY = re.compile(r"^[\s\d:()\[\]\-,.;/%={}!rsa]*$")


def fmt_date(value, spec):
    """value.strftime-style formatting with the current language's month names (English: format(value, spec))."""
    return _format_arg(value, spec, "")


def tr(template, *args):
    """A sentence built from pieces. English: exactly template.format(*args). Other languages: the translated
    template with each piece translated (strings) or formatted (numbers, dates with the language's month names).
    A template that has no translation is left as English and its pieces are NOT translated (it may be a data key),
    unless it is only punctuation around the pieces such as "{0} ({1}): {2}"."""
    if _code == "en":
        return template.format(*args) if args else template
    pattern = _table().get(template)
    if pattern is None:
        if _DISPLAY_ONLY.match(re.sub(r"\{[^}]*\}", "", template) + "{}"):
            pattern = template
        else:
            if _misses is not None:
                _misses.add(template)
            return template.format(*args)
    out = []
    for literal, field, spec, conversion in _formatter.parse(pattern):
        out.append(literal)
        if field is None:
            continue
        idx = int(field) if field.isdigit() else field
        try:
            out.append(_format_arg(args[idx], spec or "", conversion))
        except (IndexError, ValueError, TypeError):
            out.append("{" + field + "}")
    return "".join(out)


def join_list(items):
    """'A, B and C' in the current language (items are translated first)."""
    items = [((_lookup(i) or _rule(i) or i) if _code != "en" else i) if isinstance(i, str) else str(i) for i in items]
    if not items:
        return ""
    if len(items) == 1:
        return items[0]
    word = _table().get("and") if _code != "en" else None
    return ", ".join(items[:-1]) + f" {word or 'and'} " + items[-1]


# ---------------------------------------------------------------- tables whose values are translated when read
class _TDict(dict):
    def __getitem__(self, key):
        return _wrap(dict.__getitem__(self, key))

    def get(self, key, default=None):
        return _wrap(dict.get(self, key, default))

    def values(self):
        return [_wrap(v) for v in dict.values(self)]

    def items(self):
        return [(k, _wrap(v)) for k, v in dict.items(self)]


class _TList(list):
    def __getitem__(self, i):
        v = list.__getitem__(self, i)
        return _wrap(v) if not isinstance(i, slice) else [_wrap(x) for x in v]

    def __iter__(self):
        return iter([_wrap(v) for v in list.__iter__(self)])


def _wrap(value):
    if _code == "en":
        return value
    if isinstance(value, str):
        return t(value)
    if isinstance(value, tuple):
        return tuple(_wrap(v) for v in value)
    if isinstance(value, (_TDict, _TList)):
        return value
    return value


def tbl(obj):
    """Wrap a module-level table (dict / list of display strings) so its VALUES are translated on read."""
    if isinstance(obj, dict):
        return _TDict({k: tbl(v) if isinstance(v, (dict, list)) else v for k, v in obj.items()})
    if isinstance(obj, list):
        return _TList([tbl(v) if isinstance(v, (dict, list)) else v for v in obj])
    return obj
