"""Offline translation layer checks. Run from android_app/: python -m pytest tests/test_i18n.py

The readable translations live in i18n_src/; engine/i18n_hi.py and i18n_bn.py are GENERATED by
tools/build_i18n.py (letters pre-joined into private-use syllable glyphs)."""
import importlib.util
import os
import re
import sys

APP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENGINE = os.path.join(APP, "engine")
if ENGINE not in sys.path:
    sys.path.insert(0, ENGINE)

import i18n  # noqa: E402
import i18n_bn  # noqa: E402
import i18n_hi  # noqa: E402

INDIC = re.compile("[\u0900-\u097F\u0980-\u09FF]")
PUA = re.compile("[\ue000-\uf8ff]")


def _src(code):
    spec = importlib.util.spec_from_file_location(f"src_{code}", os.path.join(APP, "i18n_src", f"{code}.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_hindi_and_bengali_cover_the_same_strings():
    hi, bn = _src("hi"), _src("bn")
    assert set(hi.T) == set(bn.T), sorted(set(hi.T) ^ set(bn.T))[:5]
    assert set(i18n_hi.T) == set(hi.T) and set(i18n_bn.T) == set(bn.T), "generated files are out of date: run tools/build_i18n.py"


def test_sources_are_real_translations():
    for code in ("hi", "bn"):
        src = _src(code)
        for key, value in src.T.items():
            assert value.strip() and INDIC.search(value), (code, key, value)


def test_generated_files_use_prejoined_glyphs_only():
    for name, mod in (("hi", i18n_hi), ("bn", i18n_bn)):
        for key, value in mod.T.items():
            assert not INDIC.search(value), (name, key, "raw Indic letters would be drawn unjoined")
            assert PUA.search(value), (name, key)
        assert PUA.search(mod.NAME) and not INDIC.search(mod.NAME)


def test_generated_fonts_can_draw_every_glyph():
    from fontTools.ttLib import TTFont
    for code, mod, stem in (("hi", i18n_hi, "IndicHi"), ("bn", i18n_bn, "IndicBn")):
        for weight in ("Regular", "Bold"):
            cmap = TTFont(os.path.join(APP, "fonts", f"{stem}-{weight}.ttf")).getBestCmap()
            used = {ch for v in list(mod.T.values()) + [mod.NAME] for ch in v if PUA.match(ch)}
            assert used and all(ord(ch) in cmap for ch in used), (code, weight)


def test_placeholders_are_preserved():
    slot = re.compile(r"\{[a-z_0-9]+\}")
    for table in (i18n_hi.T, i18n_bn.T):
        for key, value in table.items():
            assert sorted(slot.findall(key)) == sorted(slot.findall(value)), (key, value)


def test_t_falls_back_to_english_and_fills_slots():
    i18n.set_language("hi")
    assert i18n.t("Home") == i18n_hi.T["Home"] and i18n.t("Home") != "Home"
    assert i18n.t("Some text nobody translated yet") == "Some text nobody translated yet"
    assert i18n.t("Age {age}", age=24) == "Age 24"          # untranslated template still fills its slot
    i18n.set_language("bn")
    assert i18n.t("Home") == i18n_bn.T["Home"]
    assert i18n.native_name("hi") == i18n_hi.NAME and i18n.native_name("en") == "English"
    i18n.set_language("xx")                                   # unknown code -> English
    assert i18n.get_language() == "en" and i18n.t("Home") == "Home"
