"""merge_bn.py - turn the translator's working files (i18n_todo/bn_NN.txt, "id<TAB>Bengali") into the readable
source file i18n_src/bn.py that tools/build_i18n.py bakes into the app.

    python tools/merge_bn.py

It also checks every translation keeps the placeholders of its English original ({0}, {1:.0f}, %s ...), because
a lost or renamed placeholder would crash or blank a sentence at run time.
"""
import glob
import json
import os
import re

APP = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TODO = os.path.join(APP, "i18n_todo")
OUT = os.path.join(APP, "i18n_src", "bn.py")

PLACEHOLDER = re.compile(r"\{[^}]*\}|%s|%d|%\.\d+f")

# Entries that are not sentences from the app code: word rules and words the code builds from a phrase.
EXTRA = {
    "{n}th (ordinal)": "{n}তম",          # 13th, 14th ... (1st-12th are listed explicitly)
    "rising": "আরোহণ", "peak": "শিখর", "setting": "অস্তগামী",
    "week": "সপ্তাহ", "Week": "সপ্তাহ",
    "now": "এখন", "day": "দিন", "days": "দিন", "year": "বছর", "years": "বছর", "months": "মাস",
}

MONTHS_SHORT = ("জানু", "ফেব", "মার্চ", "এপ্রিল", "মে", "জুন", "জুলাই", "আগস্ট", "সেপ্ট", "অক্টো", "নভে", "ডিসে")
MONTHS_LONG = ("জানুয়ারি", "ফেব্রুয়ারি", "মার্চ", "এপ্রিল", "মে", "জুন", "জুলাই", "আগস্ট", "সেপ্টেম্বর", "অক্টোবর",
               "নভেম্বর", "ডিসেম্বর")


def load_translations():
    found = {}
    paths = sorted(glob.glob(os.path.join(TODO, "bn*_[0-9]*.txt"))) + sorted(glob.glob(os.path.join(TODO, "wf", "out_[0-9]*.txt")))
    for path in paths:
        for n, line in enumerate(open(path, encoding="utf-8"), 1):
            line = line.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                continue
            ident, tab, text = line.partition("\t")
            if not ident.isdigit() or (not tab and ident != line):
                raise SystemExit(f"{os.path.basename(path)}:{n}: expected 'id<TAB>text'")
            found[int(ident)] = text.replace("\\n", "\n")
    return found


def main():
    keys = []
    for name in ("keys.json", "keys2.json", "keys_kb.json"):          # step 1, composed text of the readings, KB sentences
        path = os.path.join(TODO, name)
        if os.path.exists(path):
            keys += json.load(open(path, encoding="utf-8"))
    by_id = {k["id"]: k for k in keys}
    done = load_translations()
    table, bad, missing = {}, [], []
    for ident, k in sorted(by_id.items()):
        english = k["en"]
        if ident not in done:
            missing.append(ident)
            continue
        bn = done[ident]
        # Leading/trailing blanks and line breaks join sentence pieces together, so they must match the English
        # (editors and tools tend to trim them from the working files). An empty translation stays empty.
        if bn.strip():
            bn = re.match(r"\s*", english).group(0) + bn.strip() + re.search(r"\s*$", english).group(0)
        else:
            bn = ""
        # English plural suffixes ("house{1}" with 's') have no Bengali counterpart: dropping them is fine
        plural = {"{%d}" % i for i, a in enumerate(k.get("args", [])) if re.match(r"\s*'s'|\s*'es'|\s*\"s\"", a)}
        expected = sorted(p for p in PLACEHOLDER.findall(english) if p not in plural)
        if expected != sorted(p for p in PLACEHOLDER.findall(bn) if p not in plural):
            bad.append((ident, english, bn))
        table[english] = bn
    # extra vocabulary that is not a sentence of the app code (remedy stones, mantras, donations, colours ...)
    for path in sorted(glob.glob(os.path.join(TODO, "bn_vocab_*.txt"))):
        for line in open(path, encoding="utf-8"):
            line = line.rstrip("\n")
            if line.strip() and "\t" in line:
                english, _, bn = line.partition("\t")
                table[english] = bn
    for word, bn in EXTRA.items():
        table.setdefault(word, bn)
    # hand corrections that win over everything above: "English<TAB>Bengali" lines in bn_fix_*.txt
    for path in sorted(glob.glob(os.path.join(TODO, "bn_fix_*.txt"))):
        for line in open(path, encoding="utf-8"):
            line = line.rstrip("\n")
            if line.strip() and "\t" in line and not line.startswith("#"):
                english, _, bn = line.partition("\t")
                table[english.replace("\\n", "\n")] = bn.replace("\\n", "\n")
    unknown = sorted(set(done) - set(by_id))
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write('# -*- coding: utf-8 -*-\n"""GENERATED by tools/merge_bn.py from i18n_todo/bn_*.txt (edit those, or edit this file and\n')
        fh.write('re-run tools/build_i18n.py). Bengali (বাংলা). Key = the exact English text used in the app."""\n')
        fh.write('NAME = "বাংলা"\n')
        fh.write(f"MONTHS = {MONTHS_SHORT!r}\nMONTHS_LONG = {MONTHS_LONG!r}\n")
        fh.write("T = {\n")
        for english, bn in table.items():
            fh.write(f"    {english!r}: {bn!r},\n")
        fh.write("}\n")
    print(f"{len(table)} entries written to {OUT}")
    print(f"not translated (program keys / left English on purpose / still to do): {len(missing)} ids")
    for ident in missing[:60]:
        print("   ", ident, repr(by_id[ident]["en"][:70]))
    if unknown:
        print("ids in the bn files that are not in keys.json:", unknown)
    if bad:
        print(f"PLACEHOLDER MISMATCH in {len(bad)} entries:")
        for ident, en, bn in bad:
            print("   ", ident, "EN:", PLACEHOLDER.findall(en), "BN:", PLACEHOLDER.findall(bn))
        raise SystemExit(1)


if __name__ == "__main__":
    main()
