"""i18n.py - the app's tiny, fully OFFLINE translation layer.

Everything the app can show in Hindi or Bengali is a plain Python dict bundled
in the APK (i18n_hi.py, i18n_bn.py): no network, no translation service, no
model. English text is its own key, so a missing translation simply shows the
English original instead of failing.

NOTE: i18n_hi.py / i18n_bn.py are GENERATED by tools/build_i18n.py from the readable
i18n_src/hi.py and bn.py. Hindi/Bengali letters are pre-joined into single syllable
glyphs (private-use code points) because Kivy's text engine cannot join them itself;
the matching fonts are fonts/IndicHi-*.ttf and IndicBn-*.ttf. Always edit i18n_src/.

    from i18n import t
    t("Home")                         -> "होम" when the language is Hindi
    t("Age {age}", age=24)            -> slots are filled after translating

Names of planets, signs and the like go through name(): name("Sun") -> "सूर्य".
"""
import importlib

LANGUAGE_CODES = ["en", "hi", "bn"]
LANGUAGES = [(c, c) for c in LANGUAGE_CODES]         # (code, unused) - kept for callers that iterate

_code = "en"
_modules = {}


def set_language(code):
    global _code
    _code = code if code in LANGUAGE_CODES else "en"


def get_language():
    return _code


def _module(code):
    if code not in _modules:
        try:
            _modules[code] = importlib.import_module(f"i18n_{code}")
        except ImportError:
            _modules[code] = None
    return _modules[code]


def _table(code):
    mod = _module(code)
    return mod.T if mod else {}


def native_name(code):
    """A language's own name, ready to draw with that language's font (English -> "English")."""
    if code == "en":
        return "English"
    mod = _module(code)
    return getattr(mod, "NAME", code) if mod else code


def t(text, **slots):
    """Translate an English string (or template with {slots}); English if there is no translation."""
    if _code != "en":
        text = _table(_code).get(text) or text
    if slots:
        try:
            return text.format(**slots)
        except (KeyError, IndexError, ValueError):
            return text
    return text


def name(word):
    """Translate a single name (planet, sign, house word...); same lookup as t()."""
    return t(word)


def has_translation(text):
    return _code == "en" or bool(_table(_code).get(text))
